### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by martinjuhasz** [matiassingers/provisioning#2]
Hi,

i had an issue using provisioning in the dependency 'cert-downloader' ([see this issue](https://github.com/evi-snowm/cert-downloader/issues/2)).
The issue has been resolved in version 0.2.1 of cert-downloader. It would be nice if you could update the dependency here to use the new version and also point your ipa-metadata tool to use the then new version of provisioning.

thanks in advance

**Comment by matiassingers** [comment]
Thanks for reporting this!

See #3

**Comment by martinjuhasz** [comment]
great. thank you!
